name: typeorm-tests

services:
  backend:
    image: typeorm-tests:latest
    ports:
      - "8080:8080"

  backend-test:
    image: typeorm-tests:latest
    ports:
      - "8081:8080"
    command: npm run test
