name: typeorm-tests

services:
  backend:
    image: typeorm-tests:latest
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: "../src"
        target: /app/src

  backend-test:
    image: typeorm-tests:latest
    ports:
      - "8081:8080"
    volumes:
      - type: bind
        source: "../src"
        target: /app/src
      - type: bind
        source: "../test"
        target: /app/test
    command: npm run test:api
    depends_on:
      - backend
    environment:
      TEST_HOST: "backend"
